# Generated by Django 6.0.1 on 2026-02-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payment_enrollment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('dummy', 'Dummy')], default='dummy', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
