# Generated by Django 6.0.1 on 2026-02-10 10:40

from django.db import migrations


def backfill_payment_course(apps, schema_editor):
    """Backfill course field from course_offering for existing payments"""
    Payment = apps.get_model('courses', 'Payment')
    
    for payment in Payment.objects.all():
        if payment.course_offering and not payment.course:
            payment.course = payment.course_offering.course
            payment.save(update_fields=['course'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_payment_course_alter_payment_course_offering'),
    ]

    operations = [
        migrations.RunPython(backfill_payment_course, migrations.RunPython.noop),
    ]
