# Generated by Django 6.0.1 on 2026-02-11 09:12

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20260210_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, help_text='Upload course video', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='course_videos/')),
                ('file', models.FileField(blank=True, help_text='Upload PDF or resource file', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='course_files/')),
                ('link', models.URLField(blank=True, help_text='External link (e.g., Google Meet)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.courseoffering')),
            ],
        ),
    ]
