from rest_framework import serializers
from django.contrib.auth import get_user_model
from .models import Course, Enrollment, CourseOffering

User = get_user_model()
class CourseOfferingSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    teacher = serializers.PrimaryKeyRelatedField(read_only=True)
    course = serializers.PrimaryKeyRelatedField(queryset=Course.objects.all())
    meet_link = serializers.URLField(required=False, allow_null=True)
    class_description = serializers.CharField(required=False, allow_null=True)
    created_at = serializers.DateTimeField(read_only=True)

    course_title = serializers.ReadOnlyField(source='course.title')
    teacher_name = serializers.ReadOnlyField(source='teacher.username')

    def create(self, validated_data):
        return CourseOffering.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.meet_link = validated_data.get('meet_link', instance.meet_link)
        instance.class_description = validated_data.get('class_description', instance.class_description)
        instance.save()
        return instance

class UserSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)  # Auto-generated by DB, user can't change it
    username = serializers.CharField(max_length=150)
    email = serializers.EmailField()
    role = serializers.CharField(max_length=10)
    teaching_courses = serializers.StringRelatedField(many=True, read_only=True)
    course_offerings = CourseOfferingSerializer(many=True, read_only=True)
    enrollments = serializers.SerializerMethodField()

    def get_enrollments(self, obj):
        items = obj.enrollments.select_related('course', 'teacher').all()
        return [
            {
                'id': item.id,
                'course': {'title': item.course.title},
                'teacher': {'username': item.teacher.username}
            } 
            for item in items
        ]


class RegisterSerializer(serializers.Serializer):
    username = serializers.CharField(max_length=150)
    email = serializers.EmailField(required=False)
    password = serializers.CharField(write_only=True)
    role = serializers.CharField(default='student')

    def create(self, validated_data):
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data.get('email'),
            password=validated_data['password'],
            role=validated_data.get('role', 'student')
        )
        return user

#admin
class CourseSerializer(serializers.Serializer):
 
    id = serializers.IntegerField(read_only=True)
    title = serializers.CharField(max_length=200)
    description = serializers.CharField()
    photo = serializers.ImageField(required=False)
    created_at = serializers.DateTimeField(read_only=True)
    teachers = serializers.StringRelatedField(many=True, read_only=True)

    teacher_count = serializers.SerializerMethodField()
    
    def get_teacher_count(self, obj):
        return obj.teachers.count()
#create
    def create(self, validated_data):
        return Course.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.title = validated_data.get('title', instance.title)
        instance.description = validated_data.get('description', instance.description)
        instance.photo = validated_data.get('photo', instance.photo)
        instance.save()
        return instance


class EnrollmentSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    student = serializers.PrimaryKeyRelatedField(read_only=True)
    course = serializers.PrimaryKeyRelatedField(queryset=Course.objects.all())
    teacher = serializers.PrimaryKeyRelatedField(queryset=User.objects.all())
    enrolled_at = serializers.DateTimeField(read_only=True)

    course_title = serializers.ReadOnlyField(source='course.title')
    teacher_name = serializers.ReadOnlyField(source='teacher.username')
    student_name = serializers.ReadOnlyField(source='student.username')
    
 
    meet_link = serializers.SerializerMethodField()
    class_description = serializers.SerializerMethodField()
    
    def get_meet_link(self, obj):
        try:
            offering = CourseOffering.objects.get(teacher=obj.teacher, course=obj.course)
            return offering.meet_link
        except CourseOffering.DoesNotExist:
            return None
    
    def get_class_description(self, obj):
        try:
            offering = CourseOffering.objects.get(teacher=obj.teacher, course=obj.course)
            return offering.class_description
        except CourseOffering.DoesNotExist:
            return None

    def create(self, validated_data):
        return Enrollment.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.course = validated_data.get('course', instance.course)
        instance.teacher = validated_data.get('teacher', instance.teacher)
        instance.save()
        return instance
