from rest_framework import serializers
from django.contrib.auth import get_user_model
from .models import Course, CourseOffering #, Enrollment

User = get_user_model()
class CourseOfferingSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    teacher = serializers.PrimaryKeyRelatedField(read_only=True)
    course = serializers.PrimaryKeyRelatedField(queryset=Course.objects.all())
    meet_link = serializers.URLField(required=False, allow_null=True)
    class_description = serializers.CharField(required=False, allow_null=True)
    created_at = serializers.DateTimeField(read_only=True)

    course_title = serializers.ReadOnlyField(source='course.title')
    teacher_name = serializers.ReadOnlyField(source='teacher.username')

    def create(self, validated_data):
        return CourseOffering.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.meet_link = validated_data.get('meet_link', instance.meet_link)
        instance.class_description = validated_data.get('class_description', instance.class_description)
        instance.save()
        return instance

class UserSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)  # Auto-generated by DB, user can't change it
    username = serializers.CharField(max_length=150)
    email = serializers.EmailField()
    role = serializers.CharField(max_length=10)
    teaching_courses = serializers.StringRelatedField(many=True, read_only=True)
    course_offerings = CourseOfferingSerializer(many=True, read_only=True)
    # enrollments = serializers.SerializerMethodField()
    # 
    # def get_enrollments(self, obj):
    #     items = obj.enrollments.select_related('course', 'teacher').all()
    #     return [
    #         {
    #             'id': item.id,
    #             'course': {'title': item.course.title},
    #             'teacher': {'username': item.teacher.username}
    #         } 
    #         for item in items
    #     ]


class RegisterSerializer(serializers.Serializer):
    username = serializers.CharField(max_length=150)
    email = serializers.EmailField(required=False)
    password = serializers.CharField(write_only=True)
    role = serializers.CharField(default='student')

    def create(self, validated_data):
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data.get('email'),
            password=validated_data['password'],
            role=validated_data.get('role', 'student')
        )
        return user

#admin
class CourseSerializer(serializers.Serializer):
 
    id = serializers.IntegerField(read_only=True)
    title = serializers.CharField(max_length=200)
    description = serializers.CharField()
    created_at = serializers.DateTimeField(read_only=True)
    teacher = serializers.PrimaryKeyRelatedField(queryset=User.objects.all())
    teacher_name = serializers.ReadOnlyField(source='teacher.username')
    price = serializers.DecimalField(max_digits=10, decimal_places=2, read_only=True)
    is_free = serializers.BooleanField(read_only=True)
    formatted_price = serializers.SerializerMethodField()

    teacher_count = serializers.SerializerMethodField()
    
    def get_teacher_count(self, obj):
        # Return 1 if course has a teacher, 0 otherwise
        return 1 if obj.teacher else 0
    
    def get_formatted_price(self, obj):
        """Return formatted price with rupee symbol"""
        if obj.is_free:
            return "FREE"
        return f"₹{obj.price:,.2f}"
#create
    def create(self, validated_data):
        return Course.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.title = validated_data.get('title', instance.title)
        instance.description = validated_data.get('description', instance.description)
        instance.teacher = validated_data.get('teacher', instance.teacher)
        instance.save()
        return instance


class EnrollmentSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    student = serializers.PrimaryKeyRelatedField(read_only=True)
    course_offering = serializers.PrimaryKeyRelatedField(queryset=CourseOffering.objects.all())
    enrolled_at = serializers.DateTimeField(read_only=True)
    grade = serializers.CharField(max_length=2, required=False, allow_blank=True, allow_null=True)

    # Fields for display
    course_title = serializers.ReadOnlyField(source='course_offering.course.title')
    teacher_name = serializers.ReadOnlyField(source='course_offering.teacher.username')
    semester = serializers.ReadOnlyField(source='course_offering.semester')
    year = serializers.ReadOnlyField(source='course_offering.year')
    meet_link = serializers.ReadOnlyField(source='course_offering.meet_link')
    class_description = serializers.ReadOnlyField(source='course_offering.class_description')
    student_name = serializers.ReadOnlyField(source='student.username')

    def create(self, validated_data):
        return Enrollment.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.course_offering = validated_data.get('course_offering', instance.course_offering)
        instance.grade = validated_data.get('grade', instance.grade)
        instance.save()
        return instance
